version: '1'
services:
  postgres:
    image: 'postgres:15.2-alpine'
    container_name: postgres
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=arina
      - POSTGRES_PASSWORD=0000
      - POSTGRES_DB=gods_wiki
    restart: always
    networks:
      - backend
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data/


networks:
  backend: {}