server:
  port: ${PORT:8090}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/gods_wiki
    username: admin
    password: "0000"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog/master.xml

report:
  base-url: "https://localhost:8089"
#logging:
#  level:
#    org:
#      springframework: debug

